# Data
title: Bashar al-Idreesi
author:
  en: Bashar al-Idreesi
  ar: بشار الإدريسي
email: basharalidreesi@gmail.com
description: >-
  Lorem ipsum dolor sit amet.
baseurl: /
url: https://basharalidreesi.com
instagram: basharalidreesi
github: basharalidreesi
timezone: JO
notice:
  - <p>Thank you for your visit! This website is under construction.</p>

# Build
collections:
  works:
    title: Works
    output: false
defaults:
  - scope:
      path: ''
    values:
      layout: main
  - scope:
      path: ''
      type: 'works'
    values:
      layout: work
theme: null
sass:
  sass_dir: _sass
  style: compact
  sourcemap: never
plugins:
  - jekyll-feed
  - jekyll-sitemap
