# Data
title: Bashar al-Idreesi
author:
  en: Bashar al-Idreesi
  ar: بشار الإدريسي
email: basharalidreesi@gmail.com
description: >-
  Lorem ipsum dolor sit amet.
baseurl: /
url: https://basharalidreesi.com
instagram: basharalidreesi
github: basharalidreesi
timezone: JO

# Build
collections:
  works:
    title: Works
    output: true
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: 'works'
    values:
      title:
      figure:
      caption:
      tags:
theme: null
sass:
  sass_dir: _sass
  style: compact
  sourcemap: never
plugins:
  - jekyll-feed
  - jekyll-sitemap
